### ISSUE TITLE
spawning a navbot makes the bot not move nor do anything.

### ISSUE THREAD

**Issue by Snowywasbanned** [caxanga334/NavBot#2]
**Describe the bug**
if i rcon the navbot command to add it does not works at all like not making the bots have ai or something, but, also for some what reasons the command cannot be executed on the client,

**To Reproduce**
host a dedicated server i guess with linux and have rafmod (i'm guessing this is causing the issue)
add a navbot and yeah

**Expected behavior**
Because of using rafmod it's probably making the navbot's ai not work at all since rafmod has features to improve TFBot's ai or something

**Screenshots**
![image](https://github.com/user-attachments/assets/ddca1995-6631-4c6f-8473-1d43ccc13628)

**Please complete the following information:**
 - TF2
 - Linux
 - Dedicated
 - Extension Version: latest i guess
 - SourceMod Version: 1.12
 - Metamod: Source Version: 2.0

**Comment by caxanga334** [comment]
NavBot is in alpha stage. You should either use [Defender TFBots](https://github.com/OfficerSpy/TF2-MvM-Defender-TFBots) or [RCBot2](https://github.com/nosoop/rcbot2).

NavBot AI is fully independent and rafmod won't do anything to it unless something is directly changing the bot's UserCmds being processed by the server.

NavBot commands are server-side console commands. They can only be used on the server console.

The bot is unable to move because of a missing navigation mesh for the map.

**Comment by Snowywasbanned** [comment]
defender bots doesnt works for me btw

**Comment by caxanga334** [comment]
Download the [latest artifact](https://github.com/caxanga334/NavBot/actions/runs/11448478187) and post the output of the console command `sm_navbot_info` here please.
